language: node_js
sudo: required
dist: trusty
node_js:
  - "6"
addons:
  chrome: stable
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
after_script:
  - npm run codecov